app/hw10/config/routes.rb
Rails.application.routes.draw do
  resources :questionnaires
  root "questionnaires#index"

end

app/hw10/app/models/questionnaire.rb
# Questionnaire 只有属性没有方法。因此这个类的声明为空。
class Questionnaire < ActiveRecord::Base
end

app/hw10/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/hw10/app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :set_questionnaire, only: [:show, :edit, :update, :destroy]

  # GET /questionnaires
  def index
    @questionnaires = Questionnaire.all
  end

  # GET /questionnaires/1
  def show
  end

  # GET /questionnaires/new
  def new
    @questionnaire = Questionnaire.new
  end

  # GET /questionnaires/1/edit
  def edit
  end

  # POST /questionnaires
  def create
    @questionnaire = Questionnaire.new(questionnaire_params)

    if @questionnaire.save
      redirect_to @questionnaire, notice: 'Questionnaire was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /questionnaires/1
  def update
    if @questionnaire.update(questionnaire_params)
      redirect_to @questionnaire, notice: 'Questionnaire was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /questionnaires/1
  def destroy
    @questionnaire.destroy
    redirect_to questionnaires_url, notice: 'Questionnaire was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def questionnaire_params
      params.require(:questionnaire).permit(:name, :age, :gender, :email)
    end
end

app/hw10/app/helpers/application_helper.rb
module ApplicationHelper
end

app/hw10/app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/hw10/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hw10</title>
  <link href="http://cdn.bootcss.com/bootstrap/3.3.1/css/bootstrap.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<%= yield %>
<%= ENV["SERVER"] %>
</div>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/hw10/app/views/questionnaires/_form.html.erb
<%= form_for @questionnaire, html: { class: "form-horizontal" } do |f| %>
  <% if @questionnaire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@questionnaire.errors.count, "error") %> prohibited this questionnaire from being saved:</h2>

      <ul>
      <% @questionnaire.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-3 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :age, class: "col-sm-3 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :age, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :gender, class: "col-sm-3 control-label" %>
    <div class="col-sm-6">
      <%= f.select :gender, ["Male", "Female"], {}, { class: "form-control" } %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, class: "col-sm-3 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-6">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/hw10/app/views/questionnaires/edit.html.erb
<h1>Editing questionnaire</h1>

<%= render 'form' %>

<%= link_to 'Back', questionnaires_path %>

app/hw10/app/views/questionnaires/index.html.erb
<h1>Questionnaires</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Email</th>
      <th width="100"></th>
    </tr>
  </thead>

  <tbody>
    <% @questionnaires.each do |questionnaire| %>
      <tr>
        <td><%= questionnaire.name %></td>
        <td><%= questionnaire.age %></td>
        <td><%= questionnaire.gender %></td>
        <td><%= questionnaire.email %></td>
        <td><%= link_to 'Edit', edit_questionnaire_path(questionnaire) %> |
        <%= link_to 'Destroy', questionnaire, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Questionnaire', new_questionnaire_path %>

app/hw10/app/views/questionnaires/new.html.erb
<h1>New questionnaire</h1>

<%= render 'form' %>

<%= link_to 'Back', questionnaires_path %>

app/hw10/app/views/questionnaires/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @questionnaire.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @questionnaire.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @questionnaire.gender %>
</p>

<p>
  <strong>Email:</strong>
  <%= @questionnaire.email %>
</p>

<%= link_to 'Edit', edit_questionnaire_path(@questionnaire) %> |
<%= link_to 'Back', questionnaires_path %>